# J7 S1: RealUW + DINO + ResNet-50.
# Based on facebookresearch/dino ResNet-50 ImageNet command.

export EXP_ID="${EXP_ID:-j7}"
export DINO_ARCH="${DINO_ARCH:-resnet50}"
export DINO_OPTIMIZER="${DINO_OPTIMIZER:-sgd}"
export DINO_LR="${DINO_LR:-0.03}"
export DINO_WEIGHT_DECAY="${DINO_WEIGHT_DECAY:-1e-4}"
export DINO_WEIGHT_DECAY_END="${DINO_WEIGHT_DECAY_END:-1e-4}"
export DINO_GLOBAL_CROPS_SCALE="${DINO_GLOBAL_CROPS_SCALE:-0.14 1}"
export DINO_LOCAL_CROPS_SCALE="${DINO_LOCAL_CROPS_SCALE:-0.05 0.14}"
export DINO_EPOCHS="${DINO_EPOCHS:-100}"
export DINO_BATCH_SIZE_PER_GPU="${DINO_BATCH_SIZE_PER_GPU:-64}"
export DINO_NUM_WORKERS="${DINO_NUM_WORKERS:-10}"
export DINO_SAVECKP_FREQ="${DINO_SAVECKP_FREQ:-50}"
