#!/usr/bin/env python3
"""Diagnose RealUW SSL image loading bottlenecks.

This script checks the common reasons why RealUW self-supervised pretraining is
slow: symlinked ImageFolder data, cross-disk source distribution, large source
images, slow decode throughput, current GPU occupancy, and disk I/O pressure.
"""

import argparse
import json
import os
import random
import subprocess
import time
from collections import Counter
from pathlib import Path

try:
    from PIL import Image
except ImportError:  # pragma: no cover
    Image = None


IMG_SUFFIXES = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}


def parse_args():
    parser = argparse.ArgumentParser(
        description='Diagnose RealUW SSL image I/O and decode bottlenecks.')
    parser.add_argument(
        '--imagefolder',
        default='/media/HDD1/XCX/exp_2/REALUW_SSL/imagefolder/train/realuw',
        help='ImageFolder class directory used by DINO/MMPreTrain.')
    parser.add_argument(
        '--manifest',
        default='/media/HDD1/XCX/exp_2/REALUW_SSL/annotations/manifest.jsonl',
        help='RealUW manifest.jsonl generated by build_realuw_ssl_dataset.py.')
    parser.add_argument(
        '--header-samples',
        type=int,
        default=300,
        help='Number of images to sample for header/resolution checks.')
    parser.add_argument(
        '--decode-samples',
        type=int,
        default=1000,
        help='Number of images to sample for full RGB decode throughput.')
    parser.add_argument(
        '--seed',
        type=int,
        default=0,
        help='Random seed for deterministic sampling.')
    parser.add_argument(
        '--iostat',
        action='store_true',
        help='Run iostat -x 1 3 if available.')
    parser.add_argument(
        '--no-gpu',
        action='store_true',
        help='Skip nvidia-smi checks.')
    return parser.parse_args()


def print_section(title):
    print('\n' + '=' * 80)
    print(title)
    print('=' * 80)


def run_shell(cmd):
    subprocess.run(cmd, shell=True, check=False)


def iter_image_files(root):
    root = Path(root)
    if not root.exists():
        return []
    return [
        path for path in root.iterdir()
        if path.suffix.lower() in IMG_SUFFIXES
    ]


def summarize_paths_from_manifest(manifest):
    disk_counter = Counter()
    dataset_counter = Counter()
    sample_paths = []

    manifest = Path(manifest)
    if not manifest.exists():
        return disk_counter, dataset_counter, sample_paths

    with manifest.open('r', encoding='utf-8') as file:
        for line in file:
            if not line.strip():
                continue
            row = json.loads(line)
            source_path = row.get('source_path', '')
            dataset = row.get('dataset', 'unknown')
            dataset_counter[dataset] += 1
            if source_path.startswith('/media/'):
                parts = Path(source_path).parts
                disk = '/'.join(parts[:3]) if len(parts) >= 3 else source_path
            else:
                disk = str(Path(source_path).anchor or 'relative')
            disk_counter[disk] += 1
            if len(sample_paths) < 5:
                sample_paths.append(source_path)
    return disk_counter, dataset_counter, sample_paths


def sample_paths(paths, count):
    if count <= 0 or not paths:
        return []
    return random.sample(paths, min(count, len(paths)))


def check_image_headers(paths):
    if Image is None:
        print('PIL is not installed; skip image header check.')
        return

    sizes = []
    bad = 0
    start = time.time()
    for path in paths:
        try:
            with Image.open(path) as image:
                sizes.append(image.size)
        except Exception:
            bad += 1
    elapsed = max(time.time() - start, 1e-9)

    if not sizes:
        print('No readable image headers.')
        print('bad:', bad)
        return

    widths = [width for width, _ in sizes]
    heights = [height for _, height in sizes]
    areas = [width * height for width, height in sizes]
    print('sample:', len(sizes), 'bad:', bad)
    print('width  min/mean/max:', min(widths), sum(widths) // len(widths),
          max(widths))
    print('height min/mean/max:', min(heights), sum(heights) // len(heights),
          max(heights))
    print('area   min/mean/max:', min(areas), sum(areas) // len(areas),
          max(areas))
    print('header open speed:', round(len(sizes) / elapsed, 2), 'img/s')


def check_decode_throughput(paths):
    if Image is None:
        print('PIL is not installed; skip decode throughput check.')
        return

    ok = 0
    bad = 0
    pixels = 0
    start = time.time()
    for path in paths:
        try:
            with Image.open(path) as image:
                image.convert('RGB').load()
                pixels += image.size[0] * image.size[1]
            ok += 1
        except Exception:
            bad += 1
    elapsed = max(time.time() - start, 1e-9)

    print('decoded:', ok, 'bad:', bad, 'sec:', round(elapsed, 2))
    print('decode speed:', round(ok / elapsed, 2), 'img/s')
    print('pixel speed:', round(pixels / elapsed / 1e6, 2), 'MPix/s')


def main():
    args = parse_args()
    random.seed(args.seed)

    imagefolder = Path(args.imagefolder)
    manifest = Path(args.manifest)

    print_section('1) Path existence')
    print('imagefolder:', imagefolder, 'exists=', imagefolder.exists())
    print('manifest   :', manifest, 'exists=', manifest.exists())

    print_section('2) Symlink check')
    image_files = iter_image_files(imagefolder)
    symlinks = [path for path in image_files if path.is_symlink()]
    print('image files:', len(image_files))
    print('symlinks   :', len(symlinks))
    if image_files:
        print('symlink ratio:', '{:.2f}%'.format(
            100.0 * len(symlinks) / max(len(image_files), 1)))
    for path in symlinks[:5]:
        print('link:', path)
        print(' -> ', os.path.realpath(path))

    print_section('3) Real source disk distribution from manifest')
    disk_counter, dataset_counter, sample_sources = summarize_paths_from_manifest(
        manifest)
    print('source disks:')
    for disk, count in disk_counter.most_common():
        print('  {}: {}'.format(disk, count))
    print('top datasets:')
    for dataset, count in dataset_counter.most_common(30):
        print('  {}: {}'.format(dataset, count))
    print('sample source paths:')
    for source in sample_sources:
        print(' ', source)

    print_section('4) Image resolution sample')
    check_image_headers(sample_paths(image_files, args.header_samples))

    print_section('5) Decode throughput sample')
    check_decode_throughput(sample_paths(image_files, args.decode_samples))

    if not args.no_gpu:
        print_section('6) Current GPU state')
        run_shell(
            'nvidia-smi --query-gpu=index,memory.used,memory.free,utilization.gpu '
            '--format=csv,noheader,nounits')
        print('\nprocesses:')
        run_shell("nvidia-smi | sed -n '/Processes:/,$p'")

    print_section('7) Disk mount info')
    run_shell('df -h /media/HDD0 /media/HDD1 /media/HDD2 2>/dev/null')

    if args.iostat:
        print_section('8) Disk IO snapshot')
        run_shell(
            "command -v iostat >/dev/null && iostat -x 1 3 || "
            "echo 'iostat not installed'")
    else:
        print_section('8) Disk IO snapshot')
        print('Skipped. Re-run with --iostat to sample disk I/O.')


if __name__ == '__main__':
    main()
