#!/usr/bin/env python3
"""Restore CUT fake_B outputs to ImageNet-style class folders."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

try:
    from tqdm import tqdm
except ImportError:  # pragma: no cover
    def tqdm(iterable, **kwargs):
        return iterable


IMAGE_SUFFIXES = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}


def parse_args():
    parser = argparse.ArgumentParser(description='Restore CUT fake_B outputs.')
    parser.add_argument('--manifest', required=True,
                        help='testA manifest generated by prepare_cut_imagenet_ruod_dataset.py')
    parser.add_argument('--results-dir', required=True,
                        help='CUT results root or images/fake_B directory.')
    parser.add_argument('--out-dir', required=True)
    parser.add_argument('--overwrite', action='store_true')
    return parser.parse_args()


def collect_outputs(root: Path) -> dict[str, Path]:
    candidates = []
    if (root / 'fake_B').is_dir():
        candidates.append(root / 'fake_B')
    for path in root.rglob('fake_B'):
        if path.is_dir():
            candidates.append(path)
    candidates.append(root)

    outputs: dict[str, Path] = {}
    for directory in candidates:
        for path in directory.rglob('*'):
            if not path.is_file() or path.suffix.lower() not in IMAGE_SUFFIXES:
                continue
            stem = path.stem
            if stem.endswith('_fake_B'):
                stem = stem[:-7]
            outputs.setdefault(stem, path)
    return outputs


def main() -> None:
    args = parse_args()
    manifest = Path(args.manifest)
    results_dir = Path(args.results_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    records = [json.loads(line) for line in manifest.read_text(encoding='utf-8').splitlines() if line.strip()]
    outputs = collect_outputs(results_dir)

    written = 0
    skipped = 0
    missing = []
    for record in tqdm(records, desc='restore CUT fake_B', unit='image'):
        generated = outputs.get(record['flat_stem'])
        if generated is None:
            missing.append(record['flat_name'])
            continue
        dst_dir = out_dir / record['synset']
        dst_dir.mkdir(parents=True, exist_ok=True)
        dst = dst_dir / f"{Path(record['original_name']).stem}{generated.suffix.lower()}"
        if dst.exists() and not args.overwrite:
            skipped += 1
            continue
        shutil.copy2(generated, dst)
        written += 1

    summary = {
        'manifest': str(manifest),
        'results_dir': str(results_dir),
        'out_dir': str(out_dir),
        'records': len(records),
        'outputs_found': len(outputs),
        'written': written,
        'skipped_existing': skipped,
        'missing': len(missing),
        'missing_samples': missing[:20],
    }
    summary_path = out_dir / 'restore_cut_fake_b_summary.json'
    summary_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding='utf-8')
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == '__main__':
    main()
